In [1]:
from google.colab import files
uploaded = files.upload()

Saving career_data.csv to career_data.csv

In [2]:
import pandas as pd

df = pd.read_csv("career_data.csv")

df.head()

,Role,Required_Skills
0,Data Analyst,"Python, SQL, Excel, Power BI, Statistics"
1,Data Scientist,"Python, Machine Learning, Statistics, SQL, Dat..."
2,Machine Learning Engineer,"Python, Machine Learning, Scikit-learn, Statis..."
3,AI Engineer,"Python, Machine Learning, Deep Learning, Tenso..."
4,Java Developer,"Java, OOP, DSA, SQL"

In [3]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Role             15 non-null     object
 1   Required_Skills  15 non-null     object
dtypes: object(2)
memory usage: 372.0+ bytes

np.int64(0)

In [4]:
df.describe(include='all')

                Role                           Required_Skills
count             15                                        15
unique            15                                        15
top     Data Analyst  Python, SQL, Excel, Power BI, Statistics
freq               1                                         1

In [9]:
# User input
user_skills = input("Enter your skills (comma separated): ").lower().split(",")
user_skills = [skill.strip() for skill in user_skills]

results = []

# Process each role
for index, row in df.iterrows():

    role = row["Role"]

    # Convert required skills to list
    required_skills = [skill.strip().lower() for skill in row["Required_Skills"].split(",")]

    # Matching skills
    matched = [skill for skill in user_skills if skill in required_skills]
    score = len(matched)

    # Missing skills
    missing = [skill for skill in required_skills if skill not in user_skills]

    # Match percentage
    if len(required_skills) > 0:
        match_percent = (score / len(required_skills)) * 100
    else:
        match_percent = 0

    # Store results
    results.append([role, score, round(match_percent, 2), missing])

# Sort by best match
results.sort(key=lambda x: x[1], reverse=True)

# Output Top 3
print("\n🔥 Top 3 Career Recommendations:\n")

for i in results[:3]:
    print("Role:", i[0])
    print("Match Score:", i[1])
    print("Match %:", i[2], "%")
    print("Missing Skills:", ", ".join(i[3]))
    print("-" * 40)

# Best recommendation
best = results[0]

print("\n🏆 Best Career Suggestion:", best[0])
print("Match %:", best[2], "%")

Enter your skills (comma separated): python, sql, excel, power bi

🔥 Top 3 Career Recommendations:

Role: Data Analyst
Match Score: 4
Match %: 80.0 %
Missing Skills: statistics
----------------------------------------
Role: Business Analyst
Match Score: 3
Match %: 75.0 %
Missing Skills: communication
----------------------------------------
Role: Data Scientist
Match Score: 2
Match %: 40.0 %
Missing Skills: machine learning, statistics, data visualization
----------------------------------------

🏆 Best Career Suggestion: Data Analyst
Match %: 80.0 %